name: recipe_app
description: Recipe App

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

  #cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #state management
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1

  #routing
  auto_route: ^5.0.4

  #core_utilities
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  connectivity_plus: ^3.0.2


  #ui
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.15
  flutter_vector_icons: ^2.0.0
  carousel_slider: ^4.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  hive_generator: ^2.0.0
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1a1a1a"
  image: assets/png/splash.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/